export interface RegisterUser {
  sub: string;
  name: string;
  given_name: string;
  family_name: string;
  middle_name: string;
  nickname: string;
  preferred_username: string;
  profile: string;
  picture: string;
  website: string;
  email: string;
  email_verified: boolean;
  gender: string;
  birthdate: string;
  zoneinfo: string;
  locale: string;
  phone_number: string;
  phone_number_verified: boolean;
  // address	JSON object	;
  updated_at: number;
}

export interface Country {
  name: string;
  iso: string;
  dial_code: string;
}

// Trim or extend as needed, or swap in a full list (e.g. libphonenumber metadata).
export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', iso: 'af', dial_code: '+93' },
  { name: 'Albania', iso: 'al', dial_code: '+355' },
  { name: 'Algeria', iso: 'dz', dial_code: '+213' },
  { name: 'Andorra', iso: 'ad', dial_code: '+376' },
  { name: 'Angola', iso: 'ao', dial_code: '+244' },
  { name: 'Argentina', iso: 'ar', dial_code: '+54' },
  { name: 'Armenia', iso: 'am', dial_code: '+374' },
  { name: 'Australia', iso: 'au', dial_code: '+61' },
  { name: 'Austria', iso: 'at', dial_code: '+43' },
  { name: 'Azerbaijan', iso: 'az', dial_code: '+994' },
  { name: 'Bahamas', iso: 'bs', dial_code: '+1242' },
  { name: 'Bahrain', iso: 'bh', dial_code: '+973' },
  { name: 'Bangladesh', iso: 'bd', dial_code: '+880' },
  { name: 'Barbados', iso: 'bb', dial_code: '+1246' },
  { name: 'Belarus', iso: 'by', dial_code: '+375' },
  { name: 'Belgium', iso: 'be', dial_code: '+32' },
  { name: 'Belize', iso: 'bz', dial_code: '+501' },
  { name: 'Benin', iso: 'bj', dial_code: '+229' },
  { name: 'Bhutan', iso: 'bt', dial_code: '+975' },
  { name: 'Bolivia', iso: 'bo', dial_code: '+591' },
  { name: 'Bosnia and Herzegovina', iso: 'ba', dial_code: '+387' },
  { name: 'Botswana', iso: 'bw', dial_code: '+267' },
  { name: 'Brazil', iso: 'br', dial_code: '+55' },
  { name: 'Brunei', iso: 'bn', dial_code: '+673' },
  { name: 'Bulgaria', iso: 'bg', dial_code: '+359' },
  { name: 'Burkina Faso', iso: 'bf', dial_code: '+226' },
  { name: 'Burundi', iso: 'bi', dial_code: '+257' },
  { name: 'Cambodia', iso: 'kh', dial_code: '+855' },
  { name: 'Cameroon', iso: 'cm', dial_code: '+237' },
  { name: 'Canada', iso: 'ca', dial_code: '+1' },
  { name: 'Cape Verde', iso: 'cv', dial_code: '+238' },
  { name: 'Central African Republic', iso: 'cf', dial_code: '+236' },
  { name: 'Chad', iso: 'td', dial_code: '+235' },
  { name: 'Chile', iso: 'cl', dial_code: '+56' },
  { name: 'China', iso: 'cn', dial_code: '+86' },
  { name: 'Colombia', iso: 'co', dial_code: '+57' },
  { name: 'Comoros', iso: 'km', dial_code: '+269' },
  { name: 'Congo', iso: 'cg', dial_code: '+242' },
  { name: 'Congo (DRC)', iso: 'cd', dial_code: '+243' },
  { name: 'Costa Rica', iso: 'cr', dial_code: '+506' },
  { name: 'Croatia', iso: 'hr', dial_code: '+385' },
  { name: 'Cuba', iso: 'cu', dial_code: '+53' },
  { name: 'Cyprus', iso: 'cy', dial_code: '+357' },
  { name: 'Czech Republic', iso: 'cz', dial_code: '+420' },
  { name: 'Denmark', iso: 'dk', dial_code: '+45' },
  { name: 'Djibouti', iso: 'dj', dial_code: '+253' },
  { name: 'Dominica', iso: 'dm', dial_code: '+1767' },
  { name: 'Dominican Republic', iso: 'do', dial_code: '+1' },
  { name: 'Ecuador', iso: 'ec', dial_code: '+593' },
  { name: 'Egypt', iso: 'eg', dial_code: '+20' },
  { name: 'El Salvador', iso: 'sv', dial_code: '+503' },
  { name: 'Equatorial Guinea', iso: 'gq', dial_code: '+240' },
  { name: 'Eritrea', iso: 'er', dial_code: '+291' },
  { name: 'Estonia', iso: 'ee', dial_code: '+372' },
  { name: 'Eswatini', iso: 'sz', dial_code: '+268' },
  { name: 'Ethiopia', iso: 'et', dial_code: '+251' },
  { name: 'Fiji', iso: 'fj', dial_code: '+679' },
  { name: 'Finland', iso: 'fi', dial_code: '+358' },
  { name: 'France', iso: 'fr', dial_code: '+33' },
  { name: 'Gabon', iso: 'ga', dial_code: '+241' },
  { name: 'Gambia', iso: 'gm', dial_code: '+220' },
  { name: 'Georgia', iso: 'ge', dial_code: '+995' },
  { name: 'Germany', iso: 'de', dial_code: '+49' },
  { name: 'Ghana', iso: 'gh', dial_code: '+233' },
  { name: 'Greece', iso: 'gr', dial_code: '+30' },
  { name: 'Grenada', iso: 'gd', dial_code: '+1473' },
  { name: 'Guatemala', iso: 'gt', dial_code: '+502' },
  { name: 'Guinea', iso: 'gn', dial_code: '+224' },
  { name: 'Guinea-Bissau', iso: 'gw', dial_code: '+245' },
  { name: 'Guyana', iso: 'gy', dial_code: '+592' },
  { name: 'Haiti', iso: 'ht', dial_code: '+509' },
  { name: 'Honduras', iso: 'hn', dial_code: '+504' },
  { name: 'Hong Kong', iso: 'hk', dial_code: '+852' },
  { name: 'Hungary', iso: 'hu', dial_code: '+36' },
  { name: 'Iceland', iso: 'is', dial_code: '+354' },
  { name: 'India', iso: 'in', dial_code: '+91' },
  { name: 'Indonesia', iso: 'id', dial_code: '+62' },
  { name: 'Iran', iso: 'ir', dial_code: '+98' },
  { name: 'Iraq', iso: 'iq', dial_code: '+964' },
  { name: 'Ireland', iso: 'ie', dial_code: '+353' },
  { name: 'Israel', iso: 'il', dial_code: '+972' },
  { name: 'Italy', iso: 'it', dial_code: '+39' },
  { name: 'Ivory Coast', iso: 'ci', dial_code: '+225' },
  { name: 'Jamaica', iso: 'jm', dial_code: '+1876' },
  { name: 'Japan', iso: 'jp', dial_code: '+81' },
  { name: 'Jordan', iso: 'jo', dial_code: '+962' },
  { name: 'Kazakhstan', iso: 'kz', dial_code: '+7' },
  { name: 'Kenya', iso: 'ke', dial_code: '+254' },
  { name: 'Kiribati', iso: 'ki', dial_code: '+686' },
  { name: 'Kosovo', iso: 'xk', dial_code: '+383' },
  { name: 'Kuwait', iso: 'kw', dial_code: '+965' },
  { name: 'Kyrgyzstan', iso: 'kg', dial_code: '+996' },
  { name: 'Laos', iso: 'la', dial_code: '+856' },
  { name: 'Latvia', iso: 'lv', dial_code: '+371' },
  { name: 'Lebanon', iso: 'lb', dial_code: '+961' },
  { name: 'Lesotho', iso: 'ls', dial_code: '+266' },
  { name: 'Liberia', iso: 'lr', dial_code: '+231' },
  { name: 'Libya', iso: 'ly', dial_code: '+218' },
  { name: 'Liechtenstein', iso: 'li', dial_code: '+423' },
  { name: 'Lithuania', iso: 'lt', dial_code: '+370' },
  { name: 'Luxembourg', iso: 'lu', dial_code: '+352' },
  { name: 'Macau', iso: 'mo', dial_code: '+853' },
  { name: 'Madagascar', iso: 'mg', dial_code: '+261' },
  { name: 'Malawi', iso: 'mw', dial_code: '+265' },
  { name: 'Malaysia', iso: 'my', dial_code: '+60' },
  { name: 'Maldives', iso: 'mv', dial_code: '+960' },
  { name: 'Mali', iso: 'ml', dial_code: '+223' },
  { name: 'Malta', iso: 'mt', dial_code: '+356' },
  { name: 'Marshall Islands', iso: 'mh', dial_code: '+692' },
  { name: 'Mauritania', iso: 'mr', dial_code: '+222' },
  { name: 'Mauritius', iso: 'mu', dial_code: '+230' },
  { name: 'Mexico', iso: 'mx', dial_code: '+52' },
  { name: 'Micronesia', iso: 'fm', dial_code: '+691' },
  { name: 'Moldova', iso: 'md', dial_code: '+373' },
  { name: 'Monaco', iso: 'mc', dial_code: '+377' },
  { name: 'Mongolia', iso: 'mn', dial_code: '+976' },
  { name: 'Montenegro', iso: 'me', dial_code: '+382' },
  { name: 'Morocco', iso: 'ma', dial_code: '+212' },
  { name: 'Mozambique', iso: 'mz', dial_code: '+258' },
  { name: 'Myanmar', iso: 'mm', dial_code: '+95' },
  { name: 'Namibia', iso: 'na', dial_code: '+264' },
  { name: 'Nauru', iso: 'nr', dial_code: '+674' },
  { name: 'Nepal', iso: 'np', dial_code: '+977' },
  { name: 'Netherlands', iso: 'nl', dial_code: '+31' },
  { name: 'New Zealand', iso: 'nz', dial_code: '+64' },
  { name: 'Nicaragua', iso: 'ni', dial_code: '+505' },
  { name: 'Niger', iso: 'ne', dial_code: '+227' },
  { name: 'Nigeria', iso: 'ng', dial_code: '+234' },
  { name: 'North Korea', iso: 'kp', dial_code: '+850' },
  { name: 'North Macedonia', iso: 'mk', dial_code: '+389' },
  { name: 'Norway', iso: 'no', dial_code: '+47' },
  { name: 'Oman', iso: 'om', dial_code: '+968' },
  { name: 'Pakistan', iso: 'pk', dial_code: '+92' },
  { name: 'Palau', iso: 'pw', dial_code: '+680' },
  { name: 'Palestine', iso: 'ps', dial_code: '+970' },
  { name: 'Panama', iso: 'pa', dial_code: '+507' },
  { name: 'Papua New Guinea', iso: 'pg', dial_code: '+675' },
  { name: 'Paraguay', iso: 'py', dial_code: '+595' },
  { name: 'Peru', iso: 'pe', dial_code: '+51' },
  { name: 'Philippines', iso: 'ph', dial_code: '+63' },
  { name: 'Poland', iso: 'pl', dial_code: '+48' },
  { name: 'Portugal', iso: 'pt', dial_code: '+351' },
  { name: 'Qatar', iso: 'qa', dial_code: '+974' },
  { name: 'Romania', iso: 'ro', dial_code: '+40' },
  { name: 'Russia', iso: 'ru', dial_code: '+7' },
  { name: 'Rwanda', iso: 'rw', dial_code: '+250' },
  { name: 'Saint Kitts and Nevis', iso: 'kn', dial_code: '+1869' },
  { name: 'Saint Lucia', iso: 'lc', dial_code: '+1758' },
  { name: 'Saint Vincent and the Grenadines', iso: 'vc', dial_code: '+1784' },
  { name: 'Samoa', iso: 'ws', dial_code: '+685' },
  { name: 'San Marino', iso: 'sm', dial_code: '+378' },
  { name: 'Sao Tome and Principe', iso: 'st', dial_code: '+239' },
  { name: 'Saudi Arabia', iso: 'sa', dial_code: '+966' },
  { name: 'Senegal', iso: 'sn', dial_code: '+221' },
  { name: 'Serbia', iso: 'rs', dial_code: '+381' },
  { name: 'Seychelles', iso: 'sc', dial_code: '+248' },
  { name: 'Sierra Leone', iso: 'sl', dial_code: '+232' },
  { name: 'Singapore', iso: 'sg', dial_code: '+65' },
  { name: 'Slovakia', iso: 'sk', dial_code: '+421' },
  { name: 'Slovenia', iso: 'si', dial_code: '+386' },
  { name: 'Solomon Islands', iso: 'sb', dial_code: '+677' },
  { name: 'Somalia', iso: 'so', dial_code: '+252' },
  { name: 'South Africa', iso: 'za', dial_code: '+27' },
  { name: 'South Korea', iso: 'kr', dial_code: '+82' },
  { name: 'South Sudan', iso: 'ss', dial_code: '+211' },
  { name: 'Spain', iso: 'es', dial_code: '+34' },
  { name: 'Sri Lanka', iso: 'lk', dial_code: '+94' },
  { name: 'Sudan', iso: 'sd', dial_code: '+249' },
  { name: 'Suriname', iso: 'sr', dial_code: '+597' },
  { name: 'Sweden', iso: 'se', dial_code: '+46' },
  { name: 'Switzerland', iso: 'ch', dial_code: '+41' },
  { name: 'Syria', iso: 'sy', dial_code: '+963' },
  { name: 'Taiwan', iso: 'tw', dial_code: '+886' },
  { name: 'Tajikistan', iso: 'tj', dial_code: '+992' },
  { name: 'Tanzania', iso: 'tz', dial_code: '+255' },
  { name: 'Thailand', iso: 'th', dial_code: '+66' },
  { name: 'Timor-Leste', iso: 'tl', dial_code: '+670' },
  { name: 'Togo', iso: 'tg', dial_code: '+228' },
  { name: 'Tonga', iso: 'to', dial_code: '+676' },
  { name: 'Trinidad and Tobago', iso: 'tt', dial_code: '+1868' },
  { name: 'Tunisia', iso: 'tn', dial_code: '+216' },
  { name: 'Turkey', iso: 'tr', dial_code: '+90' },
  { name: 'Turkmenistan', iso: 'tm', dial_code: '+993' },
  { name: 'Tuvalu', iso: 'tv', dial_code: '+688' },
  { name: 'Uganda', iso: 'ug', dial_code: '+256' },
  { name: 'Ukraine', iso: 'ua', dial_code: '+380' },
  { name: 'United Arab Emirates', iso: 'ae', dial_code: '+971' },
  { name: 'United Kingdom', iso: 'gb', dial_code: '+44' },
  { name: 'United States', iso: 'us', dial_code: '+1' },
  { name: 'Uruguay', iso: 'uy', dial_code: '+598' },
  { name: 'Uzbekistan', iso: 'uz', dial_code: '+998' },
  { name: 'Vanuatu', iso: 'vu', dial_code: '+678' },
  { name: 'Vatican City', iso: 'va', dial_code: '+379' },
  { name: 'Venezuela', iso: 've', dial_code: '+58' },
  { name: 'Vietnam', iso: 'vn', dial_code: '+84' },
  { name: 'Yemen', iso: 'ye', dial_code: '+967' },
  { name: 'Zambia', iso: 'zm', dial_code: '+260' },
  { name: 'Zimbabwe', iso: 'zw', dial_code: '+263' },
];
